name: Android Build & Firebase Distribution

on:
  push:
    branches: [ "feature/add-app-distribution" ]
  pull_request:
    branches: [ "feature/add-app-distribution" ]

env:
  FLUTTER_VERSION: '3.38.9'
  JAVA_VERSION: '17'
  BUILD_TYPE: 'release'

jobs:
  build_android:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      # 3Ô∏è‚É£ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      # 4Ô∏è‚É£ Check Flutter version
      - name: Flutter version
        run: flutter --version

      # 5Ô∏è‚É£ Get dependencies
      - name: Get dependencies
        run: flutter pub get

      - name: Generate localization keys (easy_localization)
        run: flutter pub run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart

      - name: Run code generation (build_runner)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # 6Ô∏è‚É£ Build release APK
      - name: Build APK (release)
        run: flutter build apk --release

      # 7Ô∏è‚É£ Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: |
            üöÄ Android Build

            App: ${{ github.event.repository.name }}
            Version: ${{ github.run_number }}
            Build Type: ${{ env.BUILD_TYPE }}
            Branch: ${{ github.ref_name }}

            Commit:
            ${{ github.event.head_commit.message }}